pre-commit:
  parallel: false
  commands:
    format:
      glob: '*.{js,mjs,cjs,json,yml,yaml,md}'
      run: npx prettier --write {staged_files}
      stage_fixed: true

pre-push:
  commands:
    format-check:
      run: npm run format:check
